
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zwwofphqttojlgoefhzz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3d29mcGhxdHRvamxnb2VmaHp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg1Njc2MzksImV4cCI6MjA1NDE0MzYzOX0.O2nwIZTi-B26YWCupGvlu-Pd_VNs2BCH5nRtMzkK-4U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
